### ISSUE TITLE
Split client view

### ISSUE THREAD

**Issue by decoch** [dbflute/dbflute-intro#144]

**Comment by decoch** [comment]
Next action.

- Write a rough

**Comment by decoch** [comment]
inspired by toggl: https://toggl.com
![img_20190214_114939](https://user-images.githubusercontent.com/11879823/52759479-564dce00-304f-11e9-881e-5162e49f5c07.jpg)

**Comment by RyoheiYamamoto** [comment]
Use the following?
https://semantic-ui.com/collections/menu.html#inverted

**Comment by ryo-chin** [comment]
Use the following?
https://semantic-ui.com/collections/menu.html#inverted
