### ISSUE TITLE
Refactor entire code related to client

### ISSUE THREAD

**Issue by shin-kinoshita** [dbflute/dbflute-intro#195]
https://dbflute.slack.com/archives/CAQ2T8KC4/p1573705479033400

```
[Share] 11/14ずおん会やったこと
今日は主にリファクタリングどうするかの議論多めでした。
o clientName に名前を統一する // 【追記】やはりprojectNameにした
o alter を playsql に移動する
o settings を dfprop に移動する
o ClientAction 持ちすぎ問題を解決する
o ClientRowResult を消したい
```

analyzed by jflute

[change to clientName]
o clientName is many used at server but non at client
o projectName is many used at server and many-many at client
o thinking...

// and uses Project Name in document
http://dbflute.seasar.org/ja/manual/function/generator/intro/index.html#welcomeitem

// also here
http://dbflute.seasar.org/ja/manual/function/helper/emecha/newclient/index.html#clientproject

[move alter to playsql]
o web.alter.AlterAction to web.playsql.migration.alter
o only move it (with a little refactoring)

[move settings to dfprop]
o SettingsAction can update basicInfoMap.dfprop and databaseInfoMap.dfprop
o dfprop.basic.DfpropBasicAction? (for now?)

[slim ClientAction]
o split to ClientCreateAction, ClientEditAction...

[slim ClientRowResult]
o maybe not remove but slim it
o too many items so remove client-unused items

**Comment by jflute** [comment]
split PlaysqlMigrationLogic
to
PlaysqlMigrationInfoLogic
PlaysqlMigrationUpdateLogic
PlaysqlMigrationPhysicalLogic

make PlaysqlMigrationAlterAssist for PlaysqlMigrationAlterAction

**Comment by jflute** [comment]
o move SettingsUpdateLogic to DatabaseInfoLogic
o move DfpropAction's specific methods to specific actions
o move SettingsAction to dfprop.settings.DfpropSettingsAction
o rename syncschema to schemasync (only in server)
