### ISSUE TITLE
Make "then" value selectable

### ISSUE THREAD

**Issue by jflute** [dbflute/dbflute-intro#278]
o subject of has-is can be selectable
o then value of non-is  can be selectable

however, you can design effective UI.

has-is first? whole selection?

# if has-is first

```
o non-is o has-is  // RadioButton

subject
 +_______________+ // ListBox
 |[v]            |
 +_______________+

value?
 +_______________+ // TextBox
 |               |
 +_______________+
```

o if non-is, show then-values for non-is (not show value?)
o if has-is, show subjects for has-is (and show value? text box)
o default selection is non-is?

# if whole selection

```
then-value? or subject
 +______________+ // ListBox
 |[v]           |
 +______________+

value?
 +_______________+ // TextBox
 |               |
 +_______________+
```

o show then-values (non-is) and subjects (has-is) together
o if non-is selected, end
o if has-is selected, show values text box

# selection
## non-is
bad, hasPK, upperCaseBasis, lowerCaseBasis, identityIfPureIDPK, sequenceIfPureIDPK, hasCommonColumn, hasAlias, hasComment

## has-is
tableName, alias, comment, pkName, fkName, uniqueName, indexName, pk_columnName, pk_dbType, pk_size, pk_dbType_with_size

**Comment by EgumaYuto** [comment]
📝  whole selection の方がいいという話をした

**Comment by jflute** [comment]
[Feedback] SchemaPolicy画面:
Add statementした後に
o Expectedのリストボックス選択が残ってしまう
o Expectedが選択しても空扱いになる(ValidationError)
