### ISSUE TITLE
Docker イメージが稼働する Java のバージョンを最新バージョンに上げる

### ISSUE THREAD

**Issue by EgumaYuto** [dbflute/dbflute-intro#295]
## AS-IS
現在、Dockerイメージが amazoncorret8 がベースとなっているが、今後最新のJavaで稼働できることを定期的に確認できない

## TO-BE
最新バージョンのJavaで起動するように、ベースイメージを変更する

**Comment by jflute** [comment]
o OpenJDKを使ってあげるほうが無難？
o DockerHubに入ってるJDKを指定することができる
