### ISSUE TITLE
1/1/2022 リリース時点でLastaFluteとDBFluteを最新にする

### ISSUE THREAD

**Issue by EgumaYuto** [dbflute/dbflute-intro#332]
表題の通り、やりましょう

気をつける点は以下？
https://dbflute.slack.com/archives/CAQ2T8KC4/p1637840261042700?thread_ts=1637828753.034200&cid=CAQ2T8KC4

**Comment by jflute** [comment]
アップしたいのは、dbflute, lastaflute, jetty-boot, lasta-meta(lasta-doc), utflute かな。
