### ISSUE TITLE
pre-commit に lint を実行する

### ISSUE THREAD

**Issue by EgumaYuto** [dbflute/dbflute-intro#378]
## 背景
https://github.com/dbflute/dbflute-intro/issues/375 の後続Issue
lintを使えるように整備したら、開発者があまり意識しなくても利用できるようにしたい
こうすることでフロントエンドのレビューからノイズを取り除くことができる

## 対応
こちらを参考に pre-commit の設定をいれてあげる
commit 前にちゃんとフォーマットもlintも自動でかけてあげる
https://dev.classmethod.jp/articles/pre-commit/

## 完了条件
- git の commit or push 時に lint がかかる状態にする
- PRでレビューのノイズが無くなっていること

**Comment by ryo-chin** [comment]
下記issueのプルリクで husky を用いて precommit format を設定済み
https://github.com/dbflute/dbflute-intro/issues/398
