### ISSUE TITLE
Riot6, 既存コード把握のi18n.tagだよん

### ISSUE THREAD

**Issue by EgumaYuto** [dbflute/dbflute-intro#390]
対象
- app/common/i18n.tag

**Comment by jflute** [comment]
i18nは、riot6でがらりと変わるっぽいので、やらなくて良い気がする

**Comment by ryo-chin** [comment]
> i18nは、riot6でがらりと変わるっぽいので、やらなくて良い気がする

はい、まさにそのとおりなのでこちらのissueはcloseします 🙇‍♂️
