### ISSUE TITLE
Riot6, 既存コード把握のresult-view.tagだよん

### ISSUE THREAD

**Issue by EgumaYuto** [dbflute/dbflute-intro#392]
対象
- app/common/result-view.tag

プルリク: https://github.com/dbflute/dbflute-intro/pull/411

**Comment by dbflute** [comment]
くぼです。ごめんなさい、Notificationテストです。

**Comment by dbflute** [comment]
@jflute メンション入れると？

**Comment by dbflute** [comment]
そしてUnsubscribeした後

**Comment by dbflute** [comment]
@jflute まためんしょん

**Comment by dbflute** [comment]
今度はdoneの後

**Comment by dbflute** [comment]
unsubscribeしてから担当にすると？

**Comment by dbflute** [comment]
そもそも担当で来る。改めてunsubscribeした跡のコメント

**Comment by jflute** [comment]
自分がコメントすると？

**Comment by dbflute** [comment]
その後コメントすると？

**Comment by dbflute** [comment]
もっきあ

**Comment by dbflute** [comment]
@jflute そしてめんしょん
